### ISSUE TITLE
How to provide privateKey in correct format

### ISSUE THREAD

**Issue by stheine** [maitrungduc1410/node-scp-async#10]
Hi,

I try to use scp with username and ssh key - I have the `~/.ssh/id_rsa` private key file (`-----BEGIN RSA PRIVATE KEY-----`).
When I pass that file's content into privateKey, this ends with `Handshake failed: no matching host key format`.
What's wrong here? how to correctly convert that `id_rsa` format into a format acceptable for ssh/scp?

Regards
  stheine

**Comment by maitrungduc1410** [comment]
You may not read the README carefully :). In case of using `privateKey` to do SSH, you should use `fs.readFileSync` to correctly read your privateKey. Sample:
```
const scp = await scp({
      host: 'some ip',
      port: 22,
      username: 'username',
      passphrase: 'password',
      privateKey: fs.readFileSync('path_to_public_key')
    })
```

**Comment by stheine** [comment]
well, I did. missing the `privateKey` causes a different error.

I now found that I have to add these options:

```
      algorithms: {          
        serverHostKey: [     
          'ssh-dss',
        ],
      },
```

the commandline scp responded with:
```
Unable to negotiate with <ip> port 22: no matching host key type found. Their offer: ssh-dss
lost connection
```
so that provided me the info I needed.

**Comment by maitrungduc1410** [comment]
has your public key added to your server yet?
