### ISSUE TITLE
windows下scp上传目录(uploadDir)不能自动上传子文件

### ISSUE THREAD

**Issue by BigCatGit** [maitrungduc1410/node-scp-async#12]
windows下scp上传目录(uploadDir)不能自动上传子文件，而在mac上传目录是可以上传子文件的, 可以处理一下吗

**Comment by maitrungduc1410** [comment]
感谢您报告此错误，我们将尽快进行处理，并在最短的时间内通知您。

**Comment by maitrungduc1410** [comment]
您好，请升级到0.0.14版，此问题已修复，我在Windows上尝试过，并且工作正常。 如果仍有问题，请告诉我您的验证码
