### ISSUE TITLE
文档里的downloadDir()函数根本不存在

### ISSUE THREAD

**Issue by BigCatGit** [maitrungduc1410/node-scp-async#13]
文档里的downloadDir()函数，我看了index.d.ts的声明，根本没有这个函数存在
https://www.npmjs.com/package/node-scp

**Comment by maitrungduc1410** [comment]
downloadDir（）函数位于index.d.ts文件中，您可以尝试使用“ npm runkit”进行查看。

<img width="1427" alt="Screenshot 2021-02-27 at 18 12 37" src="https://user-images.githubusercontent.com/16630193/109384420-8fe88d80-7927-11eb-85c7-8b95e3d3a9d7.png">
