### ISSUE TITLE
File transfer progress monitoring

### ISSUE THREAD

**Issue by qbotas** [maitrungduc1410/node-scp-async#16]
Is it possible to monitor transfer progress?

I'm downloading big files (40GB), and rsync is not available on the other side. It takes about 2hrs to get one file.  Would be nice to have some more precise info on where am I in time.

**Comment by maitrungduc1410** [comment]
I don't think this is possible, the library uses `ssh2` under the hood, and seems like ssh2 doesn't have an option to return progress during uploading a file.

I'm finding a solution for this as this is a good feature to have

**Comment by hkors** [comment]
That would be a nice feature to have.
