### ISSUE TITLE
Import in typescript fails

### ISSUE THREAD

**Issue by jithinsk** [maitrungduc1410/node-scp-async#17]
Importing the module in typescript fails.

I have tried `import scp from "node-scp";`. When I try to use `scp.Client()` it is allowed by typescript.
But on running, it throws error `TypeError: (0 , _nodeScp.Client) is not a function`

Can you please add how to use with typescript to the documentation as well ?

**Comment by jithinsk** [comment]
To solve this, I have used

`const SCPClient = scp as unknown as (
  options: IScpOptions
) => Promise<ScpClient>;
`
Then I can use `SCPClient(options)` to create client and it works fine.

I think this is an issue with typings of the project.

**Comment by maitrungduc1410** [comment]
Thanks for your report. I fixed this issue.

Please upgrade to `0.0.15` and check README.
