### ISSUE TITLE
upload uploadDir err

### ISSUE THREAD

**Issue by changeLong** [maitrungduc1410/node-scp-async#2]
`async function test() {
    try {
        const client = await scp({
            host: 'xxxx',
            port: 22,
            username: 'root',
            password: 'xxxx',
        })
        await client.uploadDir(path.join('./dist'), '/usr/www/dist/')
        client.close() // remember to close connection after you finish
    } catch (e) {
        console.log(e)
    }
}`

directory list : 
/dist/test/1.js

but use uploadDir fn,only dist upload, no dist/test && dist/test/1.js

**Comment by maitrungduc1410** [comment]
Hi, could you try it again?

I checked and it's working fine
