### ISSUE TITLE
Distributed code (on NPM) differs from source code

### ISSUE THREAD

**Issue by tphbrok** [maitrungduc1410/node-scp-async#26]
Hi,

Upon updating to 0.0.17, I found that there is a (likely incidental) `console.log` statement in the distributed code (from NPM).

Lines 137 to 139 of node-scp/lib/index.js are:

```js
...
137  return [2 /*return*/, new Promise(function (resolve, reject) {
138    console.log('......', options)
139      _this.sftpWrapper.fastPut(localPath, remotePath, options, function (err) {
...
```

I am not able to find this `console.log` statement in the source code, otherwise I would have happily submitted a pull request to fix this.

Kind regards,

Thomas

**Comment by maitrungduc1410** [comment]
probably my mistake when publishing the library, let me fix it

**Comment by soulgalore** [comment]
Hi @maitrungduc1410 any chance you could push a new release without that console log message? Thanks :)

**Comment by maitrungduc1410** [comment]
@soulgalore  can u upgrade to 0.0.18 ?
