### ISSUE TITLE
SCP from one account to another fails authentication.

### ISSUE THREAD

**Issue by mousseq** [maitrungduc1410/node-scp-async#28]
I am trying to use node-scp to upload a file from user-a@machine-1 to user-b@machine-2. I have set up a certificate to do so and it works when scp is invoked from the command line. However, when I use node-scp specifying the certificate path and the certificate password to client, I always receive an authentication failure (all methods exhausted). If I specify the user-b@machine-2 password to node-scp instead of the certificate, it works. Is this a known issue? I am using node-scp@0.0.16 on node v18.2.0.

**Comment by maitrungduc1410** [comment]
thanks for reporting, I'll check and get back to u
