### ISSUE TITLE
Example for async/await folder download wrong

### ISSUE THREAD

**Issue by smitterer** [maitrungduc1410/node-scp-async#29]
The example for folder download using the async/await method is wrong.

It says` await client.downloadDir('./local/dir', '/server/path')` while it should be ` await client.downloadDir('/server/path', './local/dir)`
Tried it and it's working if both paths are switched against each other.

**Comment by maitrungduc1410** [comment]
sorry, my mistake, going to update README. 

Thanks for pointing out
