### ISSUE TITLE
Upload dir fails between windows client and linux server

### ISSUE THREAD

**Issue by rickybruno89** [maitrungduc1410/node-scp-async#3]
For upload directories, the code implements path join and if you want to copy from windows to unix, that path joint puts " \ " on destination directory path, and that is not compatible with unix, so, if you are in windows, the code should concat destination path with name file, instead of use path.join

**Comment by maitrungduc1410** [comment]
Thanks for your comment. I'll fix this soon

**Comment by maitrungduc1410** [comment]
@rickybruno89 , hi, this issue is fixed, you can upgrade to newer version of the package and check now
