### ISSUE TITLE
How to remove a file on remote server

### ISSUE THREAD

**Issue by smitterer** [maitrungduc1410/node-scp-async#30]
Hi,

how would I remove one or multiple file(s) from a remote folder?

Is this possible with this node?

Thanks

**Comment by maitrungduc1410** [comment]
Hi, not at the moment, I have it in my local already, will create PR by today or tmr

**Comment by maitrungduc1410** [comment]
yes, the library does support that. Use these:
- `unlink(remotePath: string)` to remove a file
- `rmdir(remotePath: string)` to remove a folder
