### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by sebastianjnuwu** [maitrungduc1410/node-scp-async#34]
The file with the Key is ok

```js
import { Client } from 'node-scp';
import fs from 'fs';

Client({
  host: 'my IP',
  port: 22,
  username: 'ubuntu',
  privateKey: fs.readFileSync('./key.pem'),
});
```

**Comment by alljinx** [comment]
Same issue here. I tested with 2 different key, the first one works well (about 1kb), the second one (about 3kb) is rejected.
It's interesting to note that both works welle with "ssh2" lib...

**Comment by thivyan** [comment]
Seems like it's sending over ssh-rsa as the algo offer to the server (even if the key is different?). This algo is no longer allowed on latest OpenSSH server versions by default.

**Comment by maitrungduc1410** [comment]
Hi Everyone, thanks for reporting issue. Can someone please give me more context or provide an example so that I can reproduce?

**Comment by sebastianjnuwu** [comment]
> Hi Everyone, thanks for reporting issue. Can someone please give me more context or provide an example so that I can reproduce?

Unfortunately when it's the authentication method by Key it doesn't work, in my case it doesn't have the password I don't know if in your package it's optional for the ssh method, anyway

**Comment by sebastianjnuwu** [comment]
> Hi Everyone, thanks for reporting issue. Can someone please give me more context or provide an example so that I can reproduce?

Is this method right? Have you checked if it logs in? 
```js
import { Client } from 'node-scp';
import fs from 'fs';

Client({
  host: 'my IP',
  port: 22,
  username: 'ubuntu',
  privateKey: fs.readFileSync('./key.pem'),
});
```

**Comment by sebastianjnuwu** [comment]
? They never gave me an answer on how to solve it.

**Comment by maitrungduc1410** [comment]
Hi @sebastianjnuwu,

please check if you have pass the passphrase for your privateKey, I really can't reproduce your issue

**Comment by sebastianjnuwu** [comment]
> Hi @sebastianjnuwu,
> 
> please check if you have pass the passphrase for your privateKey, I really can't reproduce your issue

Hello, node-scp is already working correctly, I updated my vps and the problem stopped, I don't know what to say

**Comment by maitrungduc1410** [comment]
@sebastianjnuwu glad to hear that
