### ISSUE TITLE
Progress on uploadDir

### ISSUE THREAD

**Issue by ccforeverd** [maitrungduc1410/node-scp-async#35]
Hello~ How can i see progress when use uploadDir?

**Comment by ccforeverd** [comment]
https://github.com/maitrungduc1410/node-scp-async/blob/cd1d4dc66b8a6db606ca4aed8861597fff1fdae3/src/index.ts#L138

Maybe after uploadFile add `this.emit('transfer', newSrc, newDst)`

**Comment by maitrungduc1410** [comment]
this may help you: https://github.com/maitrungduc1410/node-scp-async/issues/27

**Comment by ccforeverd** [comment]
Thanks

I want something like (currentCompletedFiles) / (totalFiles)

My use case is to upload generated files from local to remote server and it takes a long time

I don't know if there working well or something error but not throw for it's always a 'loading' in terminal

So i want to see the progress when uploading a dir

**Comment by maitrungduc1410** [comment]
> Thanks
> 
> I want something like (currentCompletedFiles) / (totalFiles)
> 
> My use case is to upload generated files from local to remote server and it takes a long time
> 
> I don't know if there working well or something error but not throw for it's always a 'loading' in terminal
> 
> So i want to see the progress when uploading a dir

it does recursively upload to remove server, so it won't calculate `totalFiles` in advance
