### ISSUE TITLE
mình không thấy  hỗ trợ cho typescript

### ISSUE THREAD

**Issue by thachtho** [maitrungduc1410/node-scp-async#39]
mình không thấy  hỗ trợ cho typescript

**Comment by maitrungduc1410** [comment]
Bạn gặp lỗi gì à?

Lib có hỗ trợ typescript nhé bạn

**Comment by thachtho** [comment]
được rồi ạ, cho mình hỏi thêm là cái này mỗi lần sử dụng phải .close(), nhưng mà trong chương trình của mình sử dụng rất nhiều chỗ, nếu không close() thì có sao không ạ.

**Comment by maitrungduc1410** [comment]
ko close thì connect vẫn sẽ ở đó và bạn có thể có memory leak.

nếu bạn sử dụng nhiều chỗ thì:
1. bạn có thể tạo connection 1 lần, và share cho toàn bộ app của bạn
2. hoặc dùng lần nào connect lần đó và close luôn
