### ISSUE TITLE
How to provide key as a string or buffer string?

### ISSUE THREAD

**Issue by kopax** [maitrungduc1410/node-scp-async#40]
Hello, we store in database private key of our ssh host, we do not have a file, do we need to create a file to use that lib ?

It would be awesome if a string/buffer string could be used, as explained in the documentation, I have tried to do : `Buffer.from(pk, 'utf-8')`, but it didn't help.

Is there a way to start from a pk string ?

Thanks :pray:

**Comment by maitrungduc1410** [comment]
nice suggestion, I'll see how to implement this

**Comment by kopax** [comment]
Actually, i just went back here to say I did a mistake, readFileSync return a buffer, and I have tried to do `Buffer.from(readFileSync(path)).toString()` , and both, string and buffer works. 

The problem is how I save the pk in database, it seems some char disappear after encoding.


Thank you for your willingness but I close so you don't waste your time :)
