### ISSUE TITLE
Download remote directory (recursive scp)

### ISSUE THREAD

**Issue by jforge** [maitrungduc1410/node-scp-async#7]
Is there maybe some plan to support download a remote directory using scp -r?
(I can imagine that you already thought about it, but for some reason it's not yet available)

**Comment by maitrungduc1410** [comment]
I'll create a release today or tomorrow for that

**Comment by macchie** [comment]
UP!

**Comment by fairsayan** [comment]
any news?

**Comment by maitrungduc1410** [comment]
Hi all,

download remote directory is available now, please upgrade to latest version `0.0.9`
