### ISSUE TITLE
Add support for ssh2 parameter `readyTimeout`

### ISSUE THREAD

**Issue by tphbrok** [maitrungduc1410/node-scp-async#8]
Hi,

I use this package all the time at work to automate deployment of front-end files, so thanks for providing us with a modern (and TypeScript compatible ❤️) `scp` client usable in TS code.

The problem I'm facing is the inability to provide a timeout when instantiating a new `node-scp` client. In my particular case, the `ssh` connection is utterly slow, meaning that the default of 20 seconds provided by `ssh2` isn't sufficient, raising a timeout error. I've manually modified `ssh2` in my `/node_modules` by setting the default of `readyTimeout` to 40 seconds, which did the trick.

Therefore, the solution to my problem (and perhaps a nice addition for other users) is adding `readyTimeout` to the options interface of `node-scp` class.

If you are busy, I'd happily help you out by adding this to the package.

**Comment by maitrungduc1410** [comment]
Thanks for your support

`readyTimeout` is available in version `0.0.8`, please update

**Comment by tphbrok** [comment]
Thanks a lot for the quick response and update!

Closing this issue.
