### ISSUE TITLE
Not working. No error being thrown.

### ISSUE THREAD

**Issue by mithunkalan** [maitrungduc1410/node-scp-async#9]
I am trying to upload a file from my stock Ubuntu to a stock raspberry pi raspbian. 
I've done your example and i'm not getting any success. 
Uploading a 160kb file, i either get nothing & the program stalls for 5+ mins. Or, it dies immediately with an 'undefined' and not via the catch block. 
After 5 attempts, i got 1 success late and no change to the code in any attempt. 
For a 3mb file, it gets to 100kb & then stalls. 

Any idea whats going on?

```
const client = await scp({
    host: "192.168.....",
    port: 22,
    username: "......",
    password: "......",
  });

try {
    let s = await client.uploadFile( "/home/.../file.jpg",  "/home/pi/file.jpg"  );
    console.log(s);
  } catch (e) {
    console.log(e);
  }
await client.close();
```

**Comment by mithunkalan** [comment]
oh, i'm using 0.0.11

**Comment by maitrungduc1410** [comment]
I just made some tests, it's working fine. Please check your connection from your Ubuntu to your Raspberry.

Carefully check if your raspberry is reachable from your Ubuntu, and allow to scp.
